# Generated by Django 4.0.2 on 2023-06-30 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('song_dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='upload_rate',
            new_name='upload_date',
        ),
    ]
